apiVersion: v1
kind: Secret
metadata:
  name: sensitive-app-secrets
type: Opaque
data:
  APP_PASSWORD: dGFyZ2V0X3Bhc3N3b3Jk # echo -n "target_password" | base64
  APP_USERNAME: dGFyZ2V0X3VzZXJuYW1l # echo -n "target_username" | base64

---

apiVersion: v1
kind: Pod
metadata:
  name: sensitive-app
  labels:
    app: target-app-1
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: sensitive-app-secrets
            key: APP_PASSWORD
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: sensitive-app-secrets
            key: APP_USERNAME
